#!/bin/sh

set -e

case "$1" in
  configure)
    if ! getent passwd _cutf-operator > /dev/null 2>&1
    then
        # The cvdnetwork group is created by cuttlefish-base
        adduser --system --disabled-password --disabled-login --home /var/empty \
                --no-create-home --quiet --force-badname --ingroup cvdnetwork _cutf-operator
    fi
    if ! getent passwd _cvd-executor > /dev/null 2>&1
    then
        adduser --system --disabled-password --disabled-login --home /var/empty \
                --no-create-home --quiet --force-badname --group _cvd-executor
        usermod -a -G cvdnetwork,kvm _cvd-executor
    fi
esac

# Automatically added by dh_installinit/13.6ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/cuttlefish-host_orchestrator" ]; then
		update-rc.d cuttlefish-host_orchestrator defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native cuttlefish-host_orchestrator $_dh_action || exit 1
	fi
fi
# End automatically added section

