#!/bin/sh
set -e
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d cuttlefish-host_orchestrator remove >/dev/null
fi
# End automatically added section
