#!/bin/sh
set -e
# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/cuttlefish-host_orchestrator" ] ; then
	invoke-rc.d --skip-systemd-native cuttlefish-host_orchestrator stop || exit 1
fi
# End automatically added section
