#!/bin/sh

set -e

case "$1" in
    (configure)
    if ! getent group cvdnetwork > /dev/null 2>&1
    then
        addgroup --system cvdnetwork
    fi

    # Create the kvm group when running inside a docker container.
    if test -f /.dockerenv && ( ! getent group kvm > /dev/null 2>&1 )
    then
        addgroup --system kvm
    fi
    ;;
esac

# Automatically added by dh_installinit/13.6ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/cuttlefish-host-resources" ]; then
		update-rc.d cuttlefish-host-resources defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native cuttlefish-host-resources $_dh_action || exit 1
	fi
fi
# End automatically added section

